version: '3'

networks:
  dbg:
  woocommerce_woocommerce:
    external: true


volumes:
    mysql-data:
    mongo-data:

services:
  #Console
  console:
    container_name: dbg_console
    build:
      context: ./console
    volumes:
      - ./data/dataswitcher_aws:/dataswitcher:cached
      - ./data/databrydge_aws:/databrydge:cached
    depends_on:
      - mariadb
      - mongodb
      - sqs
    networks:
      - dbg
      - woocommerce_woocommerce
    command: tail -f /dev/null
    environment:
      PHP_IDE_CONFIG: "serverName=xdebug.test"
  #Console
  console_test:
    container_name: dbg_console_test
    build:
      context: ./console_test
    volumes:
      - ./data/dataswitcher_aws:/dataswitcher:cached
      - ./data/databrydge_aws:/databrydge:cached
    depends_on:
      - mariadb
      - mongodb
      - sqs
    networks:
      - dbg
      - woocommerce_woocommerce
    command: tail -f /dev/null  
  #Web
  web:
    container_name: dbg_web
    build: 
      context: ./build
      args:
        - USER_ID=10000
    volumes:
      - ./data/dataswitcher_aws:/var/www/html/dataswitcher_aws/:cached
      - ./data/databrydge_aws:/var/www/html/databrydge_aws/:cached
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    depends_on: 
      - mariadb
      - mongodb
      - sqs
    networks:
      - dbg
      - woocommerce_woocommerce

  #MongoDB
  mongodb:
    image: mongo:latest
    container_name: dbg_mongodb
    environment:
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo-data:/data/db
    ports:
      - 127.0.0.1:27019:27017
    networks:
      - dbg
    command:
      'mongod --logpath=/dev/null' # --quiet

  #MariaDB
  mariadb:
    container_name: dbg_mariadb
    image: mariadb:10.3
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 127.0.0.1:3309:3306
    networks:
      - dbg
    command:
      'mysqld --innodb-flush-method=fsync --wait_timeout=28800'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_DATABASE: db
  #PhpMyAdmin
  phpmyadmin:
    container_name: dbg_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 127.0.0.1:8180:80
    networks:
      - dbg
    depends_on: 
      - mariadb
    links:
      - mariadb
    environment:
      PMA_PORT: 3306
      PMA_HOST: mariadb
  #Mailcatcher
  mailcatcher:
    container_name: dbg_mailcatcher
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - dbg
  #sqs
  sqs:
    container_name: dbg_sqs
    image: roribio16/alpine-sqs
    ports:
      - 9325:9325
      - 9324:9324
    networks:
      - dbg
    volumes:
      - ./alpine-sqs:/opt/custom
